### PR TITLE
Added support for customized headers/footers in xlsx

### PR DESCRIPTION
**Pull request by pescamillam**
It allows to add customized headers and footers in xlsx to be shown just on print preview

### CODE REVIEW

**Comment by shertage** [comment]
Hello Peter,

Thank you for your interest in JasperReports. We tested [this commit](https://github.com/Jaspersoft/jasperreports/pull/1/commits/ccf43eec850b10e5ffd740f89970e8f157754a00) using a JRXML sample. However, when exporting the report to XLSX, headers and footers were not properly displayed in print preview. We had to manually set the page margins and the page scale in order to render all headers and footers visible.
Could you post a sample JRXML that works as expected? 
I'm attaching our JRXML sample, so you can test it by yourself. Just unzip the file, then replace the XlsFormulaReport.jrxml file in the xlsformula/reports sample directory with the unzipped one, and run the sample to see the results. The xlsformula directory can be found in the demo/samples directory within the JR source distro.
Please let us know about your findings.

Thank you,
Sanda
[XlsFormulaReport.zip](https://github.com/Jaspersoft/jasperreports/files/482662/XlsFormulaReport.zip)

**Comment by pescamillam** [comment]
In order for them to show I just added a commit which reverts a commit so the margins are configurable, after that you must set a margin bigger than 0 on top and bottom for them to show up for example this jrxml 
[XlsFormulaReport.jrxml.zip](https://github.com/Jaspersoft/jasperreports/files/483777/XlsFormulaReport.jrxml.zip)

**Comment by pescamillam** [comment]
@shertage bump

**Comment by teodord** [comment]
Hi, Peter

I don't think the revert is needed.

When we set the print margins to zero, we did it because the report page margins were already part of the sheet, represented as a first empty row and first empty column in the sheet.
So we are not going to revert that as it was a good change made at the time.

After further testing, we realized that Excel has 6 types of printing margins:
top, left, bottom right and header and footer.

The header and footer margins are independent of top and bottom margins. They do not add up.

Also, even with all margins set to zero, the headers and footers are printed OK.
Initially, we were confused by the fact that the Excel file produced by our exporters creates opaque white cells by default. The header and footer were not appearing because they were overlapped by white background cells.
But if you make the cells transparent or use the net.sf.jasperreports.export.xls.white.page.background configuration property to have them generated transparent by default, the headers and footers will come through in the print preview.

We are ready to accept your initial fix for XLSX headers and footers. If you could revert the revert, I would then try to merge your pull request performing a "squash", so that all your 3 commits appear as one, and thus we get rid of the back and forth with regards to the margins issue.

Also, please contact me at teodord@users.sourceforge.net because I need you to sign a copyright agreement with us, so that we can incorporate your commit in our open source project.

Thank you,
Teodor

**Comment by pescamillam** [comment]
@teodord 

Hey, I just reverted the revert, also I removed an unnused property in the file.

So far what I can tell on the tests I made the margins need to be set I haven't looked at the transparent cells you mention but I know you have worked more in that than me, so I will just follow.

I just sent you an email to sign the agreement and the code change can be included as it is something we need to work with xlsx or jasperreports recent versions, thank you for your review.

--
Peter Escamilla

**Pull request merged**
